package com.app.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum MessageEnum {
    ACCEPTED("ACCEPTED"),
    BAD_REQUEST("BAD_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    SUCCESS("SUCCESS"),
    SUCCESS_PRCS("SUCCESS_PRCS"),
    SUCCESS_SRCH("SUCCESS_SRCH"),
    SUCCESS_ADD("SUCCESS_ADD"),
    SUCCESS_MOD("SUCCESS_MOD"),
    SUCCESS_DEL("SUCCESS_DEL"),
    SUCCESS_UPL("SUCCESS_UPL"),
    SUCCESS_APL("SUCCESS_APL"),
    SUCCESS_INIT("SUCCESS_INIT"),
    SUCCESS_PYM("SUCCESS_PYM"),
    NO_DATA("NO_DATA"),
    NO_DATA_SLCT("NO_DATA_SLCT"),
    NO_DATA_SRCH("NO_DATA_SRCH"),
    DEFAULT("DEFAULT"),
    FIELD_INVALID_FAIL("FIELD_INVALID_FAIL"),
    ERROR_SRCH("ERROR_SRCH"),
    ERROR_ADD("ERROR_ADD"),
    ERROR_MOD("ERROR_MOD"),
    ERROR_DEL("ERROR_DEL"),
    COMMON_VALID_ETC1("COMMON_VALID_ETC1"),
    COMMON_VALID_ETC2("COMMON_VALID_ETC2"),
    COMMON_VALID_ETC4("COMMON_VALID_ETC4"),
    ERROR_VALID_DATE("ERROR_VALID_DATE"),
    ERROR_VALID_CUSTOM("ERROR_VALID_CUSTOM");
    
    @Getter
    private String code;
}
